# Generated by Django 6.0 on 2025-12-08 15:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('books', 'Books'), ('keys', 'Keys'), ('wallet', 'Wallet/Purse'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('returned', 'Returned'), ('claimed', 'Claimed')], default='lost', max_length=20)),
                ('location_lost', models.CharField(max_length=200)),
                ('location_found', models.CharField(blank=True, max_length=200)),
                ('date_lost', models.DateField()),
                ('date_found', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='lost_found/')),
                ('contact_info', models.CharField(max_length=200)),
                ('is_resolved', models.BooleanField(default=False)),
                ('reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('books', 'Books'), ('keys', 'Keys'), ('wallet', 'Wallet/Purse'), ('other', 'Other')], max_length=50)),
                ('location_found', models.CharField(max_length=200)),
                ('date_found', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='lost_found/')),
                ('contact_info', models.CharField(max_length=200)),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL)),
                ('lost_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_matches', to='lost_found.lostitem')),
            ],
            options={
                'ordering': ['-date_found'],
            },
        ),
        migrations.AddIndex(
            model_name='lostitem',
            index=models.Index(fields=['status'], name='lost_found__status_4f9d13_idx'),
        ),
        migrations.AddIndex(
            model_name='lostitem',
            index=models.Index(fields=['category'], name='lost_found__categor_bac338_idx'),
        ),
    ]
